name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test on Swift ${{ matrix.swift_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift_version: ["5.1"]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: ${{ matrix.swift_version }}
    - run: swift test --verbose
